-- Vehicle data imported from Car projects/vehicles.lua
-- Organized by category for easy filtering

Config.Vehicles = {
    compacts = {
        { model = 'asbo', name = 'Asbo', brand = 'Maxwell' },
        { model = 'blista', name = 'Blista', brand = 'Dinka' },
        { model = 'brioso', name = 'Brioso R/A', brand = 'Grotti' },
        { model = 'club', name = 'Club', brand = 'BF' },
        { model = 'dilettante', name = 'Dilettante', brand = 'Karin' },
        { model = 'issi2', name = 'Issi', brand = 'Weeny' },
        { model = 'panto', name = 'Panto', brand = 'Benefactor' },
        { model = 'prairie', name = 'Prairie', brand = 'Bollokan' },
        { model = 'rhapsody', name = 'Rhapsody', brand = 'Declasse' },
        { model = 'weevil', name = 'Weevil', brand = 'BF' },
    },
    sedans = {
        { model = 'asea', name = 'Asea', brand = 'Declasse' },
        { model = 'asterope', name = 'Asterope', brand = 'Karin' },
        { model = 'cog55', name = 'Cognoscenti 55', brand = 'Enus' },
        { model = 'cognoscenti', name = 'Cognoscenti', brand = 'Enus' },
        { model = 'emperor', name = 'Emperor', brand = 'Albany' },
        { model = 'fugitive', name = 'Fugitive', brand = 'Cheval' },
        { model = 'glendale', name = 'Glendale', brand = 'Benefactor' },
        { model = 'ingot', name = 'Ingot', brand = 'Vulcar' },
        { model = 'intruder', name = 'Intruder', brand = 'Karin' },
        { model = 'premier', name = 'Premier', brand = 'Declasse' },
        { model = 'primo', name = 'Primo', brand = 'Albany' },
        { model = 'regina', name = 'Regina', brand = 'Dundreary' },
        { model = 'stafford', name = 'Stafford', brand = 'Enus' },
        { model = 'stanier', name = 'Stanier', brand = 'Vapid' },
        { model = 'stratum', name = 'Stratum', brand = 'Zirconium' },
        { model = 'stretch', name = 'Stretch', brand = 'Dundreary' },
        { model = 'superd', name = 'Super Diamond', brand = 'Enus' },
        { model = 'surge', name = 'Surge', brand = 'Cheval' },
        { model = 'tailgater', name = 'Tailgater', brand = 'Obey' },
        { model = 'warrener', name = 'Warrener', brand = 'Vulcar' },
        { model = 'washington', name = 'Washington', brand = 'Albany' },
    },
    suvs = {
        { model = 'baller', name = 'Baller', brand = 'Gallivanter' },
        { model = 'baller2', name = 'Baller II', brand = 'Gallivanter' },
        { model = 'bjxl', name = 'BeeJay XL', brand = 'Karin' },
        { model = 'cavalcade', name = 'Cavalcade', brand = 'Albany' },
        { model = 'cavalcade2', name = 'Cavalcade II', brand = 'Albany' },
        { model = 'contender', name = 'Contender', brand = 'Vapid' },
        { model = 'dubsta', name = 'Dubsta', brand = 'Benefactor' },
        { model = 'fq2', name = 'FQ2', brand = 'Fathom' },
        { model = 'granger', name = 'Granger', brand = 'Declasse' },
        { model = 'gresley', name = 'Gresley', brand = 'Bravado' },
        { model = 'habanero', name = 'Habanero', brand = 'Emperor' },
        { model = 'huntley', name = 'Huntley S', brand = 'Enus' },
        { model = 'landstalker', name = 'Landstalker', brand = 'Dundreary' },
        { model = 'patriot', name = 'Patriot', brand = 'Mammoth' },
        { model = 'radi', name = 'Radius', brand = 'Vapid' },
        { model = 'rocoto', name = 'Rocoto', brand = 'Obey' },
        { model = 'seminole', name = 'Seminole', brand = 'Canis' },
        { model = 'serrano', name = 'Serrano', brand = 'Benefactor' },
        { model = 'toros', name = 'Toros', brand = 'Pegassi' },
        { model = 'xls', name = 'XLS', brand = 'Benefactor' },
    },
    coupes = {
        { model = 'cogcabrio', name = 'Cognoscenti Cabrio', brand = 'Enus' },
        { model = 'exemplar', name = 'Exemplar', brand = 'Dewbauchee' },
        { model = 'f620', name = 'F620', brand = 'Ocelot' },
        { model = 'felon', name = 'Felon', brand = 'Lampadati' },
        { model = 'felon2', name = 'Felon GT', brand = 'Lampadati' },
        { model = 'jackal', name = 'Jackal', brand = 'Ocelot' },
        { model = 'oracle2', name = 'Oracle XS', brand = 'Übermacht' },
        { model = 'sentinel', name = 'Sentinel', brand = 'Übermacht' },
        { model = 'sentinel2', name = 'Sentinel XS', brand = 'Übermacht' },
        { model = 'windsor', name = 'Windsor', brand = 'Enus' },
        { model = 'windsor2', name = 'Windsor Drop', brand = 'Enus' },
        { model = 'zion', name = 'Zion', brand = 'Übermacht' },
        { model = 'zion2', name = 'Zion Cabrio', brand = 'Übermacht' },
    },
    muscle = {
        { model = 'blade', name = 'Blade', brand = 'Vapid' },
        { model = 'buccaneer', name = 'Buccaneer', brand = 'Albany' },
        { model = 'chino', name = 'Chino', brand = 'Vapid' },
        { model = 'coquette3', name = 'Coquette BlackFin', brand = 'Invetero' },
        { model = 'dominator', name = 'Dominator', brand = 'Vapid' },
        { model = 'dukes', name = 'Dukes', brand = 'Imponte' },
        { model = 'gauntlet', name = 'Gauntlet', brand = 'Bravado' },
        { model = 'hotknife', name = 'Hotknife', brand = 'Vapid' },
        { model = 'phoenix', name = 'Phoenix', brand = 'Imponte' },
        { model = 'ruiner', name = 'Ruiner', brand = 'Imponte' },
        { model = 'sabregt', name = 'Sabre GT Turbo', brand = 'Declasse' },
        { model = 'slamvan', name = 'Slam Van', brand = 'Vapid' },
        { model = 'stalion', name = 'Stallion', brand = 'Declasse' },
        { model = 'tampa', name = 'Tampa', brand = 'Declasse' },
        { model = 'vigero', name = 'Vigero', brand = 'Declasse' },
        { model = 'virgo', name = 'Virgo', brand = 'Albany' },
        { model = 'voodoo', name = 'Voodoo', brand = 'Declasse' },
        { model = 'yosemite', name = 'Yosemite', brand = 'Declasse' },
    },
    sportsclassics = {
        { model = 'ardent', name = 'Ardent', brand = 'Ocelot' },
        { model = 'btype', name = 'Roosevelt', brand = 'Albany' },
        { model = 'casco', name = 'Casco', brand = 'Lampadati' },
        { model = 'deluxo', name = 'Deluxo', brand = 'Imponte' },
        { model = 'dynasty', name = 'Dynasty', brand = 'Weeny' },
        { model = 'fagaloa', name = 'Fagaloa', brand = 'Vulcar' },
        { model = 'feltzer3', name = 'Stirling GT', brand = 'Benefactor' },
        { model = 'gt500', name = 'GT500', brand = 'Grotti' },
        { model = 'infernus2', name = 'Infernus Classic', brand = 'Pegassi' },
        { model = 'jb700', name = 'JB 700', brand = 'Dewbauchee' },
        { model = 'mamba', name = 'Mamba', brand = 'Declasse' },
        { model = 'monroe', name = 'Monroe', brand = 'Pegassi' },
        { model = 'peyote', name = 'Peyote', brand = 'Vapid' },
        { model = 'pigalle', name = 'Pigalle', brand = 'Lampadati' },
        { model = 'stinger', name = 'Stinger', brand = 'Grotti' },
        { model = 'stingergt', name = 'Stinger GT', brand = 'Grotti' },
        { model = 'tornado', name = 'Tornado', brand = 'Declasse' },
        { model = 'ztype', name = 'Z-Type', brand = 'Truffade' },
    },
    sports = {
        { model = 'alpha', name = 'Alpha', brand = 'Albany' },
        { model = 'banshee', name = 'Banshee', brand = 'Bravado' },
        { model = 'bestiagts', name = 'Bestia GTS', brand = 'Grotti' },
        { model = 'buffalo', name = 'Buffalo', brand = 'Bravado' },
        { model = 'buffalo2', name = 'Buffalo S', brand = 'Bravado' },
        { model = 'carbonizzare', name = 'Carbonizzare', brand = 'Grotti' },
        { model = 'comet2', name = 'Comet', brand = 'Pfister' },
        { model = 'coquette', name = 'Coquette', brand = 'Invetero' },
        { model = 'elegy2', name = 'Elegy RH8', brand = 'Annis' },
        { model = 'feltzer2', name = 'Feltzer', brand = 'Benefactor' },
        { model = 'furoregt', name = 'Furore GT', brand = 'Lampadati' },
        { model = 'jester', name = 'Jester', brand = 'Dinka' },
        { model = 'kuruma', name = 'Kuruma', brand = 'Karin' },
        { model = 'massacro', name = 'Massacro', brand = 'Dewbauchee' },
        { model = 'ninef', name = '9F', brand = 'Obey' },
        { model = 'ninef2', name = '9F Cabrio', brand = 'Obey' },
        { model = 'penumbra', name = 'Penumbra', brand = 'Maibatsu' },
        { model = 'rapidgt', name = 'Rapid GT', brand = 'Dewbauchee' },
        { model = 'rapidgt2', name = 'Rapid GT Convertible', brand = 'Dewbauchee' },
        { model = 'schafter3', name = 'Schafter V12', brand = 'Benefactor' },
        { model = 'schwarzer', name = 'Schwartzer', brand = 'Benefactor' },
        { model = 'sultan', name = 'Sultan', brand = 'Karin' },
        { model = 'surano', name = 'Surano', brand = 'Benefactor' },
        { model = 'verlierer2', name = 'Verlierer', brand = 'Bravado' },
    },
    super = {
        { model = 'adder', name = 'Adder', brand = 'Truffade' },
        { model = 'autarch', name = 'Autarch', brand = 'Överflöd' },
        { model = 'bullet', name = 'Bullet', brand = 'Vapid' },
        { model = 'cheetah', name = 'Cheetah', brand = 'Grotti' },
        { model = 'cyclone', name = 'Cyclone', brand = 'Coil' },
        { model = 'entityxf', name = 'Entity XF', brand = 'Överflöd' },
        { model = 'fmj', name = 'FMJ', brand = 'Vapid' },
        { model = 'gp1', name = 'GP1', brand = 'Progen' },
        { model = 'infernus', name = 'Infernus', brand = 'Pegassi' },
        { model = 'italigtb', name = 'Itali GTB', brand = 'Progen' },
        { model = 'krieger', name = 'Krieger', brand = 'Benefactor' },
        { model = 'osiris', name = 'Osiris', brand = 'Pegassi' },
        { model = 'penetrator', name = 'Penetrator', brand = 'Ocelot' },
        { model = 'pfister811', name = '811', brand = 'Pfister' },
        { model = 'prototipo', name = 'X80 Proto', brand = 'Grotti' },
        { model = 'reaper', name = 'Reaper', brand = 'Pegassi' },
        { model = 't20', name = 'T20', brand = 'Progen' },
        { model = 'tempesta', name = 'Tempesta', brand = 'Pegassi' },
        { model = 'turismor', name = 'Turismo R', brand = 'Grotti' },
        { model = 'tyrus', name = 'Tyrus', brand = 'Progen' },
        { model = 'vacca', name = 'Vacca', brand = 'Pegassi' },
        { model = 'voltic', name = 'Voltic', brand = 'Coil' },
        { model = 'xa21', name = 'XA-21', brand = 'Ocelot' },
        { model = 'zentorno', name = 'Zentorno', brand = 'Pegassi' },
    },
    motorcycles = {
        { model = 'akuma', name = 'Akuma', brand = 'Dinka' },
        { model = 'bagger', name = 'Bagger', brand = 'WMC' },
        { model = 'bati', name = 'Bati 801', brand = 'Pegassi' },
        { model = 'bati2', name = 'Bati 801RR', brand = 'Pegassi' },
        { model = 'bf400', name = 'BF400', brand = 'Nagasaki' },
        { model = 'carbonrs', name = 'Carbon RS', brand = 'Nagasaki' },
        { model = 'chimera', name = 'Chimera', brand = 'Nagasaki' },
        { model = 'cliffhanger', name = 'Cliffhanger', brand = 'Western' },
        { model = 'daemon', name = 'Daemon', brand = 'WMC' },
        { model = 'double', name = 'Double-T', brand = 'Dinka' },
        { model = 'enduro', name = 'Enduro', brand = 'Dinka' },
        { model = 'esskey', name = 'Esskey', brand = 'Pegassi' },
        { model = 'faggio', name = 'Faggio Sport', brand = 'Pegassi' },
        { model = 'fcr', name = 'FCR 1000', brand = 'Pegassi' },
        { model = 'hakuchou', name = 'Hakuchou', brand = 'Shitzu' },
        { model = 'hexer', name = 'Hexer', brand = 'LCC' },
        { model = 'lectro', name = 'Lectro', brand = 'Principe' },
        { model = 'manchez', name = 'Manchez', brand = 'Maibatsu' },
        { model = 'nemesis', name = 'Nemesis', brand = 'Principe' },
        { model = 'pcj', name = 'PCJ-600', brand = 'Shitzu' },
        { model = 'ruffian', name = 'Ruffian', brand = 'Pegassi' },
        { model = 'sanchez', name = 'Sanchez', brand = 'Maibatsu' },
        { model = 'sovereign', name = 'Sovereign', brand = 'WMC' },
        { model = 'thrust', name = 'Thrust', brand = 'Dinka' },
        { model = 'vader', name = 'Vader', brand = 'Shitzu' },
        { model = 'vindicator', name = 'Vindicator', brand = 'Dinka' },
        { model = 'vortex', name = 'Vortex', brand = 'Pegassi' },
    },
    offroad = {
        { model = 'bfinjection', name = 'Bf Injection', brand = 'BF' },
        { model = 'bifta', name = 'Bifta', brand = 'BF' },
        { model = 'blazer', name = 'Blazer', brand = 'Nagasaki' },
        { model = 'brawler', name = 'Brawler', brand = 'Coil' },
        { model = 'caracara2', name = 'Caracara 4x4', brand = 'Vapid' },
        { model = 'dubsta3', name = 'Dubsta 6x6', brand = 'Benefactor' },
        { model = 'dune', name = 'Dune Buggy', brand = 'BF' },
        { model = 'hellion', name = 'Hellion', brand = 'Annis' },
        { model = 'kalahari', name = 'Kalahari', brand = 'Canis' },
        { model = 'kamacho', name = 'Kamacho', brand = 'Canis' },
        { model = 'mesa', name = 'Mesa', brand = 'Canis' },
        { model = 'rancherxl', name = 'Rancher XL', brand = 'Declasse' },
        { model = 'rebel2', name = 'Rebel', brand = 'Vapid' },
        { model = 'riata', name = 'Riata', brand = 'Vapid' },
        { model = 'sandking', name = 'Sandking XL', brand = 'Vapid' },
        { model = 'sandking2', name = 'Sandking SWB', brand = 'Vapid' },
        { model = 'trophytruck', name = 'Trophy Truck', brand = 'Vapid' },
        { model = 'vagrant', name = 'Vagrant', brand = 'Maxwell' },
        { model = 'verus', name = 'Verus', brand = 'Dinka' },
    },
    emergency = {
        { model = 'ambulance', name = 'Ambulance', brand = 'Brute' },
        { model = 'fbi', name = 'FIB Buffalo', brand = 'Bravado' },
        { model = 'fbi2', name = 'FIB SUV', brand = 'Declasse' },
        { model = 'firetruk', name = 'Fire Truck', brand = 'MTL' },
        { model = 'lguard', name = 'Lifeguard', brand = 'Declasse' },
        { model = 'pbus', name = 'Prison Bus', brand = 'Brute' },
        { model = 'police', name = 'Police Cruiser', brand = 'Vapid' },
        { model = 'police2', name = 'Police Cruiser 2', brand = 'Bravado' },
        { model = 'police3', name = 'Police Cruiser 3', brand = 'Vapid' },
        { model = 'police4', name = 'Unmarked Cruiser', brand = 'Vapid' },
        { model = 'policeb', name = 'Police Bike', brand = 'Western' },
        { model = 'policet', name = 'Police Transport', brand = 'Brute' },
        { model = 'pranger', name = 'Police Ranger', brand = 'Vapid' },
        { model = 'predator', name = 'Predator Boat', brand = 'Shitzu' },
        { model = 'riot', name = 'Police Riot', brand = 'Brute' },
        { model = 'riot2', name = 'RCV Tank', brand = 'Brute' },
        { model = 'sheriff', name = 'Sheriff Cruiser', brand = 'Vapid' },
        { model = 'sheriff2', name = 'Sheriff SUV', brand = 'Declasse' },
    },
}

-- Vehicle categories mapping
Config.VehicleCategories = {
    { id = 'compacts', name = 'Compacts', icon = 'car' },
    { id = 'sedans', name = 'Sedans', icon = 'car' },
    { id = 'suvs', name = 'SUVs', icon = 'truck' },
    { id = 'coupes', name = 'Coupes', icon = 'car-side' },
    { id = 'muscle', name = 'Muscle', icon = 'car-burst' },
    { id = 'sportsclassics', name = 'Sports Classics', icon = 'car-side' },
    { id = 'sports', name = 'Sports', icon = 'car-side' },
    { id = 'super', name = 'Super', icon = 'gauge-high' },
    { id = 'motorcycles', name = 'Motorcycles', icon = 'motorcycle' },
    { id = 'offroad', name = 'Off-Road', icon = 'truck-monster' },
    { id = 'industrial', name = 'Industrial', icon = 'truck-flatbed' },
    { id = 'utility', name = 'Utility', icon = 'wrench' },
    { id = 'vans', name = 'Vans', icon = 'van-shuttle' },
    { id = 'cycles', name = 'Bicycles', icon = 'bicycle' },
    { id = 'boats', name = 'Boats', icon = 'ship' },
    { id = 'helicopters', name = 'Helicopters', icon = 'helicopter' },
    { id = 'planes', name = 'Planes', icon = 'plane' },
    { id = 'service', name = 'Service', icon = 'screwdriver-wrench' },
    { id = 'emergency', name = 'Emergency', icon = 'siren-on' },
    { id = 'military', name = 'Military', icon = 'shield-halved' },
    { id = 'commercial', name = 'Commercial', icon = 'truck-pickup' },
    { id = 'trains', name = 'Trains', icon = 'train' },
    { id = 'openwheel', name = 'Open Wheel', icon = 'car-side' },
}
